apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: virtual-vacation
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /tmp/postgres-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: virtual-vacation
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /tmp/redis-data

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer