# GitLeaks Configuration for Virtual Vacation
# This file defines rules for detecting secrets in the codebase

title = "Virtual Vacation GitLeaks Configuration"
description = "Security configuration to detect secrets and sensitive information"

[extend]
# Use the default gitleaks config as a base
useDefault = true

[[rules]]
id = "virtual-vacation-api-keys"
description = "Virtual Vacation API Keys"
regex = '''(?i)(VITE_|API_KEY|ACCESS_TOKEN|SECRET_KEY).*[=:]\s*['""]?[a-zA-Z0-9_\-\.]{20,}['""]?'''
keywords = [
    "VITE_GOOGLE_MAPS_API_KEY",
    "VITE_OPENWEATHER_API_KEY", 
    "VITE_MAPBOX_ACCESS_TOKEN",
    "VITE_UNSPLASH_ACCESS_KEY",
    "VITE_NEWS_API_KEY",
    "JWT_SECRET",
    "SESSION_SECRET",
    "FREESOUND_API_KEY"
]

[[rules]]
id = "database-urls"
description = "Database connection strings"
regex = '''(?i)(mongodb|postgresql|mysql|redis)://[^\s'"]+'''
keywords = [
    "DATABASE_URL",
    "MONGODB_URI", 
    "REDIS_URL"
]

[[rules]]
id = "docker-secrets" 
description = "Docker and container secrets"
regex = '''(?i)(DOCKER|CONTAINER).*[=:]\s*['""]?[a-zA-Z0-9_\-\.]{10,}['""]?'''
keywords = [
    "DOCKERHUB_TOKEN",
    "DOCKER_PASSWORD"
]

# Allowlist for test files and documentation
[allowlist]
description = "Allowlist for Virtual Vacation project"
paths = [
    ".env.example",
    ".env.template", 
    "README.md",
    "docs/",
    "**/*.md",
    "**/test/**",
    "**/*.test.ts",
    "**/*.test.tsx",
    "**/*.spec.ts"
]

# Allowlist for development/example values
regexes = [
    "test_.*_secret",
    "example_.*_key",
    "demo_.*_token",
    "placeholder_.*"
]

commits = [
    # Add specific commit SHAs to ignore if needed
]

stopwords = [
    "example",
    "test", 
    "demo",
    "placeholder",
    "sample",
    "template"
]
