# ============================================================================
# DATABASE SERVICES - PostgreSQL & Redis (TESTING)
# ============================================================================
# Simplified for testing with single replicas
# ============================================================================

---
# POSTGRESQL STATEFULSET (TESTING - 1 REPLICA)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: virtual-vacation
  labels:
    app: virtual-vacation
    component: database
    service: postgres
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        component: database
    spec:
      serviceAccountName: virtual-vacation-sa
      automountServiceAccountToken: false
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: virtual-vacation-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: virtual-vacation-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: virtual-vacation-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
              storage: "10Gi"
            limits:
              memory: "512Mi"
              cpu: "250m"
              storage: "20Gi"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - vacation_user
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - vacation_user
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init-config
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        labels:
          app: virtual-vacation
          component: database
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: "standard"

---
# REDIS DEPLOYMENT (TESTING - 1 REPLICA)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: virtual-vacation
  labels:
    app: virtual-vacation
    component: cache
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        component: cache
    spec:
      serviceAccountName: virtual-vacation-sa
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: redis:7.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
              storage: "5Gi"
            limits:
              memory: "256Mi"
              cpu: "100m"
              storage: "10Gi"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: redis-data
          emptyDir: {}

---
# POSTGRESQL SERVICE
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: virtual-vacation
  labels:
    app: virtual-vacation
    component: database
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
# REDIS SERVICE
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: virtual-vacation
  labels:
    app: virtual-vacation
    component: cache
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP

---
# POSTGRESQL INIT CONFIGMAP
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-config
  namespace: virtual-vacation
data:
  init.sql: |
    -- Create extensions
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

    -- Create indexes for better performance
    CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cities_country_code ON cities(country_code);
    CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cities_coordinates ON cities(latitude, longitude);
    CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cities_popularity ON cities(popularity_score DESC);
    CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user_favorites_user ON user_favorites(user_id);
    CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user_visits_user ON user_visits(user_id);
    CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_radio_stations_country ON radio_stations(country_code);
