# ============================================================================
# BACKEND SERVICE - Node.js/Express API (TESTING - 1 REPLICA)
# ============================================================================
# Simplified for testing environment
# ============================================================================

---
# BACKEND DEPLOYMENT (TESTING - 1 REPLICA)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: virtual-vacation
  labels:
    app: virtual-vacation
    component: backend
    service: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        component: backend
    spec:
      serviceAccountName: virtual-vacation-sa
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: virtual-vacation-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: virtual-vacation-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: virtual-vacation-config
                  key: PORT
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: virtual-vacation-config
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: virtual-vacation-config
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: virtual-vacation-secrets
                  key: JWT_SECRET
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: virtual-vacation-secrets
                  key: SESSION_SECRET
            - name: GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: virtual-vacation-secrets
                  key: GOOGLE_MAPS_API_KEY
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: virtual-vacation-secrets
                  key: OPENWEATHER_API_KEY
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: virtual-vacation-config
                  key: CORS_ORIGIN
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: virtual-vacation-config
                  key: LOG_LEVEL
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: tmp-volume
          emptyDir: {}
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres-service -p 5432 -U vacation_user; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
              echo "PostgreSQL is ready!"
        - name: wait-for-redis
          image: redis:7.2-alpine
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              until redis-cli -h redis-service ping | grep -q PONG; do
                echo "Waiting for Redis..."
                sleep 2
              done
              echo "Redis is ready!"

---
# BACKEND SERVICE
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: virtual-vacation
  labels:
    app: virtual-vacation
    component: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP

---
# UPLOADS PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: virtual-vacation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "standard"
