global:
  smtp_smarthost: "localhost:587"
  smtp_from: "alertmanager@virtual-vacation.com"
  smtp_auth_username: ""
  smtp_auth_password: ""

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "slack-notifications"
  routes:
    - match:
        severity: critical
      receiver: "slack-notifications"
      continue: true

receivers:
  - name: "slack-notifications"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: "#alerts"
        send_resolved: true
        title: "{{ .GroupLabels.alertname }}"
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        icon_emoji: ":warning:"
        username: "Virtual Vacation Alert Manager"

  - name: "email-notifications"
    email_configs:
      - to: "admin@temitayocharles.online"
        headers:
          subject: "Virtual Vacation Alert"
        html: |
          {{ range .Alerts }}
          <h2>{{ .Annotations.summary }}</h2>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
          <p><strong>Time:</strong> {{ .StartsAt.Format "2006-01-02 15:04:05" }}</p>
          <hr>
          {{ end }}
