apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
  - name: PostgreSQL
    type: postgres
    url: postgres-service:5432
    database: virtual_vacation
    user: vacation_user
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 10
      connMaxLifetime: 14400
  - name: Redis
    type: redis-datasource
    url: redis-service:6379
    jsonData:
      client: standalone
